<a href="https://colab.research.google.com/github/AndreyPreobrazhenskiy/ML_Task/blob/main/Exicercies_Pandas_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Импортируйте Pandas в Jupyter Notebook.

In [96]:
# напишите свой код тут
import pandas as pd

# 1. Основыные методы работы с dataframe.

2. Создайте DataFrame из словаря, где ключами будут названия столбцов, а значениями - списки значений этих столбцов.

In [97]:
data = {
    'Name': ['Alica', 'Boris', 'Slava', 'Dmitriy', 'Evgenia','Boris','Dmitriy'],
    'last_name':['Larin','Ivanov','Sidorov','Alekseev','Petrov', 'Lebedev', 'Aksenov'],
    'Age': [24, 27, 22, 32, 29, 44, 15],
    'City': ['Moscow', 'Moscow', 'Saint Peterburg', np.nan, 'Moscow', 'Saint Peterburg','Saint Peterburg'],
    'is_closed': [False, True, False, True, False,  True, False],
    'home_town':['Samara', 'Saratov', 'Saint Peterburg', np.nan, 'Moscow', 'Moscow','Kirov'],
    'in_group':[True, True, False, False, True, True, False],
    'male_dummy':[0, 1, 1, 1, 0, 1, 1],
    'likes_memes':[5, 8, 44, np.nan, 1, 12, 11]
}

In [98]:
# напишите свой код тут
import numpy as np
data = {
    'Name': ['Alica', 'Boris', 'Slava', 'Dmitriy', 'Evgenia', 'Boris', 'Dmitriy'],
    'last_name': ['Larin', 'Ivanov', 'Sidorov', 'Alekseev', 'Petrov', 'Lebedev', 'Aksenov'],
    'Age': [24, 27, 22, 32, 29, 44, 15],
    'City': ['Moscow', 'Moscow', 'Saint Peterburg', np.nan, 'Moscow', 'Saint Peterburg', 'Saint Peterburg'],
    'is_closed': [False, True, False, True, False, True, False],
    'home_town': ['Samara', 'Saratov', 'Saint Peterburg', np.nan, 'Moscow', 'Moscow', 'Kirov'],
    'in_group': [True, True, False, False, True, True, False],
    'male_dummy': [0, 1, 1, 1, 0, 1, 1],
    'likes_memes': [5, 8, 44, np.nan, 1, 12, 11]
}
df = pd.DataFrame(data)
df

,Name,last_name,Age,City,is_closed,home_town,in_group,male_dummy,likes_memes
0,Alica,Larin,24,Moscow,False,Samara,True,0,5.0
1,Boris,Ivanov,27,Moscow,True,Saratov,True,1,8.0
2,Slava,Sidorov,22,Saint Peterburg,False,Saint Peterburg,False,1,44.0
3,Dmitriy,Alekseev,32,NaN,True,NaN,False,1,NaN
4,Evgenia,Petrov,29,Moscow,False,Moscow,True,0,1.0
5,Boris,Lebedev,44,Saint Peterburg,True,Moscow,True,1,12.0
6,Dmitriy,Aksenov,15,Saint Peterburg,False,Kirov,False,1,11.0

3. Сохраните DataFrame в CSV-файл.

Сохраните созданный датафрейм в файл people.csv (.to_csv()).

In [99]:
# напишите свой код тут
df.to_csv('people.csv')

4. Загрузите данные из созданного CSV-файла people.csv в новый DataFrame с именем df и проверьте его содержимое с помощью командой pd.read_csv().

Аргументов у нее очень много, критически важные:

- filepath_or_buffer - текстовая строка с названием (адресом) файла
- sep - разделитель между данными
- header - номер строки, в которой в файле указаны названия столбцов, None, если нет
- names - список с названиями колонок
- index_col - или номер столбца, или список, или ничего - названия строк

In [100]:
# напишите свой код тут
df = pd.read_csv('people.csv')
df

,Unnamed: 0,Name,last_name,Age,City,is_closed,home_town,in_group,male_dummy,likes_memes
0,0,Alica,Larin,24,Moscow,False,Samara,True,0,5.0
1,1,Boris,Ivanov,27,Moscow,True,Saratov,True,1,8.0
2,2,Slava,Sidorov,22,Saint Peterburg,False,Saint Peterburg,False,1,44.0
3,3,Dmitriy,Alekseev,32,NaN,True,NaN,False,1,NaN
4,4,Evgenia,Petrov,29,Moscow,False,Moscow,True,0,1.0
5,5,Boris,Lebedev,44,Saint Peterburg,True,Moscow,True,1,12.0
6,6,Dmitriy,Aksenov,15,Saint Peterburg,False,Kirov,False,1,11.0

---

Есть несколько методов, которые мы используем сразу, как загрузили файл:
- [head()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.head.html): выводит первые 5 строк таблицы. Если задать в скобках число, то покажет ровно столько строк :)
- [info()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.info.html): показывает сводную информацию о таблице; сколько записей, сколько колонок, сколько непустых записей в таблице,
- [tail()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.tail.html): работает как head(), только наоборот, печатает с конца

На всякий случай, это **методы**. Их можно применять к датафрейму и столбцу, т.е. используем их так: <br>
**[Имя датафрейма].[Название метода с круглыми скобками]**
- df.head()
- df.tail()
- df.info()

----


На основную информацию по столбцам можно посмотреть с помощью метода `.info()`. Напротив каждого названия столбца можно увидеть, сколько в нём заполненных ячеек.

5. Выведите на экран первые и последние 3 строки DataFrame.

In [101]:
# напишите свой код тут
print(df.head(3))

   Unnamed: 0   Name last_name  Age             City  is_closed  \
0           0  Alica     Larin   24           Moscow      False
1           1  Boris    Ivanov   27           Moscow       True
2           2  Slava   Sidorov   22  Saint Peterburg      False

         home_town  in_group  male_dummy  likes_memes
0           Samara      True           0          5.0
1          Saratov      True           1          8.0
2  Saint Peterburg     False           1         44.0

In [102]:
# напишите свой код тут
print(df.tail(3))

   Unnamed: 0     Name last_name  Age             City  is_closed home_town  \
4           4  Evgenia    Petrov   29           Moscow      False    Moscow
5           5    Boris   Lebedev   44  Saint Peterburg       True    Moscow
6           6  Dmitriy   Aksenov   15  Saint Peterburg      False     Kirov

   in_group  male_dummy  likes_memes
4      True           0          1.0
5      True           1         12.0
6     False           1         11.0

6. Получите общую информацию о DataFrame, включая количество строк и столбцов, типы данных и количество ненулевых значений. (метод info)

In [103]:
# напишите свой код тут
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   7 non-null      int64
 1   Name         7 non-null      object
 2   last_name    7 non-null      object
 3   Age          7 non-null      int64
 4   City         6 non-null      object
 5   is_closed    7 non-null      bool
 6   home_town    6 non-null      object
 7   in_group     7 non-null      bool
 8   male_dummy   7 non-null      int64
 9   likes_memes  6 non-null      float64
dtypes: bool(2), float64(1), int64(3), object(4)
memory usage: 594.0+ bytes

----------
### Поля
Кроме методов, у датафреймом есть еще поля. Это справочная информация о датафрейме. Список полей
<a href="https://pandas.pydata.org/pandas-docs/stable/reference/frame.html"> здесь </a>.

Чаще всего мы используем поля:
- **columns**: названия колонок
- **index**: названия строк
- **shape**: размеры датафрейма, кол-во строк и столбцов

Использование:

**[Имя датафрейма].[Имя поля]**

- df.columns
- df.index
- df.shape

Обратите внимание: нет круглых скобок!

7. Выясните сколько в таблице строк и столбцов (метод shape).

In [104]:
# напишите свой код тут
df.shape

(7, 10)

8. Выведите на экран названия всех колонок таблицы (метод columns)

In [105]:
# напишите свой код тут
df.columns

Index(['Unnamed: 0', 'Name', 'last_name', 'Age', 'City', 'is_closed',
       'home_town', 'in_group', 'male_dummy', 'likes_memes'],
      dtype='object')

#2. Базовые навыки по работе с табличками

### Выбор колонки

Чтобы вытащить столбец, у нему нужно через квадратные скобки обратиться по имени.

In [106]:
# цепляем head(), чтобы не получить слишком много напечатанных имен
df['Name'].head()

0      Alica
1      Boris
2      Slava
3    Dmitriy
4    Evgenia
Name: Name, dtype: object

In [107]:
# обратите внимание, что в квадратные скобки мы записали только 1 объект - лист с названиями колонок.
t =df[['City', 'Name']].head()
t

              City     Name
0           Moscow    Alica
1           Moscow    Boris
2  Saint Peterburg    Slava
3              NaN  Dmitriy
4           Moscow  Evgenia

Можно создавать новые колонки. Например, мы можем взять все имена и фамилии, записать их через пробел и положить в новую колонку.

In [108]:
t['first_last_name'] = df['Name'] + ' ' + df['last_name']
t.head()

              City     Name   first_last_name
0           Moscow    Alica       Alica Larin
1           Moscow    Boris      Boris Ivanov
2  Saint Peterburg    Slava     Slava Sidorov
3              NaN  Dmitriy  Dmitriy Alekseev
4           Moscow  Evgenia    Evgenia Petrov

### Выбор подряд идущих строк

Если в квадратных скобках указать диапазон, то можно выбрать несколько строк, идущих друг за другом

In [109]:
df[:2]

,Unnamed: 0,Name,last_name,Age,City,is_closed,home_town,in_group,male_dummy,likes_memes
0,0,Alica,Larin,24,Moscow,False,Samara,True,0,5.0
1,1,Boris,Ivanov,27,Moscow,True,Saratov,True,1,8.0

In [110]:
df[1:4]

,Unnamed: 0,Name,last_name,Age,City,is_closed,home_town,in_group,male_dummy,likes_memes
1,1,Boris,Ivanov,27,Moscow,True,Saratov,True,1,8.0
2,2,Slava,Sidorov,22,Saint Peterburg,False,Saint Peterburg,False,1,44.0
3,3,Dmitriy,Alekseev,32,NaN,True,NaN,False,1,NaN

---
### Уникальные значения и частотые таблицы

Очень частой операцией является нахождение уникальных значений в колонке. В зависимости от задачи есть два метода.
- [unique()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.unique.html): возвращает массив уникальных значений в колонке - к нему можем применять только обычный питон
- [drop_duplicates()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop_duplicates.html): удаляет дублирующиеся строчки в датафрейме/колонке и возвращает соответственно датафрейм или колонку - к ним можем дальше применять пандасовские методы

- [value_counts()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.value_counts.html): считает частотную таблицу, т.е. сколько раз мы встретили значение в колонке

9. Вытащите из таблички колону с городом (city), примените к ней метод, который оставит в колонке только уникальные названия городов, `.unique()`.

In [111]:
# напишите свой код тут
df['City'].unique()

array(['Moscow', 'Saint Peterburg', nan], dtype=object)

10. Сколько всего городов есть в данных?

In [112]:
# напишите свой код тут
df['City'].nunique()

2

11. Найдите количество уникальных значений в каждом столбце DataFrame.

In [113]:
# напишите свой код тут
df.nunique()

Unnamed: 0     7
Name           5
last_name      7
Age            7
City           2
is_closed      2
home_town      5
in_group       2
male_dummy     2
likes_memes    6
dtype: int64

12. Добавьте новый столбец Salary с произвольными значениями зарплат для каждого человека.

In [114]:
# напишите свой код тут
df['Salary'] = [400000, 190000, 130000, 70000, 230000, 150000, 100000]
df

,Unnamed: 0,Name,last_name,Age,City,is_closed,home_town,in_group,male_dummy,likes_memes,Salary
0,0,Alica,Larin,24,Moscow,False,Samara,True,0,5.0,400000
1,1,Boris,Ivanov,27,Moscow,True,Saratov,True,1,8.0,190000
2,2,Slava,Sidorov,22,Saint Peterburg,False,Saint Peterburg,False,1,44.0,130000
3,3,Dmitriy,Alekseev,32,NaN,True,NaN,False,1,NaN,70000
4,4,Evgenia,Petrov,29,Moscow,False,Moscow,True,0,1.0,230000
5,5,Boris,Lebedev,44,Saint Peterburg,True,Moscow,True,1,12.0,150000
6,6,Dmitriy,Aksenov,15,Saint Peterburg,False,Kirov,False,1,11.0,100000

13. Измените значение возраста (столбец Age) для любого одного человека.

In [115]:
# напишите свой код тут
df.loc[2, 'Age'] = 64
df

,Unnamed: 0,Name,last_name,Age,City,is_closed,home_town,in_group,male_dummy,likes_memes,Salary
0,0,Alica,Larin,24,Moscow,False,Samara,True,0,5.0,400000
1,1,Boris,Ivanov,27,Moscow,True,Saratov,True,1,8.0,190000
2,2,Slava,Sidorov,64,Saint Peterburg,False,Saint Peterburg,False,1,44.0,130000
3,3,Dmitriy,Alekseev,32,NaN,True,NaN,False,1,NaN,70000
4,4,Evgenia,Petrov,29,Moscow,False,Moscow,True,0,1.0,230000
5,5,Boris,Lebedev,44,Saint Peterburg,True,Moscow,True,1,12.0,150000
6,6,Dmitriy,Aksenov,15,Saint Peterburg,False,Kirov,False,1,11.0,100000

14. Какая доля людей закрыла профиль (is_closed)?

In [116]:
# напишите свой код тут
df['is_closed'].mean()

np.float64(0.42857142857142855)

15. Отфильтруйте строки DataFrame, где возраст больше 25 лет.

In [117]:
# напишите свой код тут
df[df['Age'] > 25]

,Unnamed: 0,Name,last_name,Age,City,is_closed,home_town,in_group,male_dummy,likes_memes,Salary
1,1,Boris,Ivanov,27,Moscow,True,Saratov,True,1,8.0,190000
2,2,Slava,Sidorov,64,Saint Peterburg,False,Saint Peterburg,False,1,44.0,130000
3,3,Dmitriy,Alekseev,32,NaN,True,NaN,False,1,NaN,70000
4,4,Evgenia,Petrov,29,Moscow,False,Moscow,True,0,1.0,230000
5,5,Boris,Lebedev,44,Saint Peterburg,True,Moscow,True,1,12.0,150000

16. Отфильтруйте строки, где город равен "Moscow".

In [118]:
# напишите свой код тут
df[df['City'] == "Moscow"]

,Unnamed: 0,Name,last_name,Age,City,is_closed,home_town,in_group,male_dummy,likes_memes,Salary
0,0,Alica,Larin,24,Moscow,False,Samara,True,0,5.0,400000
1,1,Boris,Ivanov,27,Moscow,True,Saratov,True,1,8.0,190000
4,4,Evgenia,Petrov,29,Moscow,False,Moscow,True,0,1.0,230000

17. Попробуйте вытащить ту же самую колонку и посчитать по ней, как часто, какой город встречается в данных, `.value_counts()`

In [119]:
# напишите свой код тут
df['City'].value_counts()

City
Moscow             3
Saint Peterburg    3
Name: count, dtype: int64

18. Выведите на экран $2$ самых популярных городов в датафрейме

In [120]:
# напишите свой код тут
df['City'].value_counts().head(2)

City
Moscow             3
Saint Peterburg    3
Name: count, dtype: int64

19. Сгруппируйте данные по столбцу City и найдите средний возраст людей для каждого города. .groupby()

In [121]:
# напишите свой код тут
df.groupby('City')['Age'].mean()

City
Moscow             26.666667
Saint Peterburg    41.000000
Name: Age, dtype: float64

20. Используйте loc, чтобы выбрать строки с именем "Alica" и "Evgenia" и вывести соответствующие данные.

In [122]:
# напишите свой код тут
df.loc[(df['Name'] == 'Alica') | (df['Name'] == 'Evgenia')]

,Unnamed: 0,Name,last_name,Age,City,is_closed,home_town,in_group,male_dummy,likes_memes,Salary
0,0,Alica,Larin,24,Moscow,False,Samara,True,0,5.0,400000
4,4,Evgenia,Petrov,29,Moscow,False,Moscow,True,0,1.0,230000

21. Используйте loc, чтобы изменить значение зарплаты для человека по имени "Dmitriy" на 70000.

In [123]:
# напишите свой код тут
df.loc[df['Name'] == 'Dmitriy', 'Salary'] = 70000
df

,Unnamed: 0,Name,last_name,Age,City,is_closed,home_town,in_group,male_dummy,likes_memes,Salary
0,0,Alica,Larin,24,Moscow,False,Samara,True,0,5.0,400000
1,1,Boris,Ivanov,27,Moscow,True,Saratov,True,1,8.0,190000
2,2,Slava,Sidorov,64,Saint Peterburg,False,Saint Peterburg,False,1,44.0,130000
3,3,Dmitriy,Alekseev,32,NaN,True,NaN,False,1,NaN,70000
4,4,Evgenia,Petrov,29,Moscow,False,Moscow,True,0,1.0,230000
5,5,Boris,Lebedev,44,Saint Peterburg,True,Moscow,True,1,12.0,150000
6,6,Dmitriy,Aksenov,15,Saint Peterburg,False,Kirov,False,1,11.0,70000

22. Используйте loc, чтобы выбрать и вывести данные всех людей старше 30 лет.

In [124]:
# напишите свой код тут
df.loc[df['Age'] > 30]

,Unnamed: 0,Name,last_name,Age,City,is_closed,home_town,in_group,male_dummy,likes_memes,Salary
2,2,Slava,Sidorov,64,Saint Peterburg,False,Saint Peterburg,False,1,44.0,130000
3,3,Dmitriy,Alekseev,32,NaN,True,NaN,False,1,NaN,70000
5,5,Boris,Lebedev,44,Saint Peterburg,True,Moscow,True,1,12.0,150000

23. Сколько уникальных мужских имён встречается?

In [125]:
# напишите свой код тут
df.loc[df['male_dummy'] == 1, 'Name'].nunique()

3

24. Выведите два самых популярных мужских имени

In [126]:
# напишите свой код тут
df.loc[df['male_dummy'] == 1, 'Name'].value_counts().head(2)

Name
Boris      2
Dmitriy    2
Name: count, dtype: int64

25. Сколько в среднем лайков ставят под мемы девушки (колонка likes_memes)

In [127]:
# напишите свой код тут
df.loc[df['male_dummy'] == 0, 'likes_memes'].mean()

np.float64(3.0)

26. Сколько суммарно лайков оставили студенты в группе с мемами?

In [128]:
# напишите свой код тут
df['likes_memes'].sum()

np.float64(81.0)

27. Сколько в среднем лайков приходится на одного человека, подписанного на группу (колонка in_group)

In [129]:
# напишите свой код тут
df.loc[df['in_group'] == 1, 'likes_memes'].mean()

np.float64(6.5)

28. Сколько лайков поставили люди, которые не подписаны на группу?

In [130]:
# напишите свой код тут
df.loc[df['in_group'] == 0, 'likes_memes'].sum()

np.float64(55.0)

29. Выведите на экран колонки, в которых нет ни одного пропуска.

In [131]:
# напишите свой код тут
df.columns[df.notna().all()]

Index(['Unnamed: 0', 'Name', 'last_name', 'Age', 'is_closed', 'in_group',
       'male_dummy', 'Salary'],
      dtype='object')

30.  Сейчас число лайков измеряется по шкале от $0$ до $44$. В машинном обучении довольно часто возникает желание поменять у данных шкалу, в которой они измерены. Такая процедура называется скалированием. Давайте переведём лайки с отрезка $[0, 44]$ на отрезок $[0, 1]$. Делать это будем по формуле:

        x_new = (x-min)/(max-min)
    
        min = минимальный элемент в столбце
        max = максимальный элемент в столбце
        
Получившийся результат запишем в колонку `like_memes_scal`.

In [132]:
# напишите свой код тут
df['like_memes_scal'] = (df['likes_memes'] - df['likes_memes'].min()) / (df['likes_memes'].max() - df['likes_memes'].min())
df

,Unnamed: 0,Name,last_name,Age,City,is_closed,home_town,in_group,male_dummy,likes_memes,Salary,like_memes_scal
0,0,Alica,Larin,24,Moscow,False,Samara,True,0,5.0,400000,0.093023
1,1,Boris,Ivanov,27,Moscow,True,Saratov,True,1,8.0,190000,0.162791
2,2,Slava,Sidorov,64,Saint Peterburg,False,Saint Peterburg,False,1,44.0,130000,1.000000
3,3,Dmitriy,Alekseev,32,NaN,True,NaN,False,1,NaN,70000,NaN
4,4,Evgenia,Petrov,29,Moscow,False,Moscow,True,0,1.0,230000,0.000000
5,5,Boris,Lebedev,44,Saint Peterburg,True,Moscow,True,1,12.0,150000,0.255814
6,6,Dmitriy,Aksenov,15,Saint Peterburg,False,Kirov,False,1,11.0,70000,0.232558

31. Найдите суммарную зарплату для каждого города

In [133]:
# напишите свой код тут
df.groupby('City')['Salary'].sum()

City
Moscow             820000
Saint Peterburg    350000
Name: Salary, dtype: int64

32. Используйте where, чтобы заменить все значения возраста, которые меньше 25, на NaN.

In [134]:
# напишите свой код тут
df['Age'] = df['Age'].where(df['Age'] >= 25)
df

,Unnamed: 0,Name,last_name,Age,City,is_closed,home_town,in_group,male_dummy,likes_memes,Salary,like_memes_scal
0,0,Alica,Larin,NaN,Moscow,False,Samara,True,0,5.0,400000,0.093023
1,1,Boris,Ivanov,27.0,Moscow,True,Saratov,True,1,8.0,190000,0.162791
2,2,Slava,Sidorov,64.0,Saint Peterburg,False,Saint Peterburg,False,1,44.0,130000,1.000000
3,3,Dmitriy,Alekseev,32.0,NaN,True,NaN,False,1,NaN,70000,NaN
4,4,Evgenia,Petrov,29.0,Moscow,False,Moscow,True,0,1.0,230000,0.000000
5,5,Boris,Lebedev,44.0,Saint Peterburg,True,Moscow,True,1,12.0,150000,0.255814
6,6,Dmitriy,Aksenov,NaN,Saint Peterburg,False,Kirov,False,1,11.0,70000,0.232558

33. Используйте where, чтобы заменить все значения зарплаты, которые меньше 60000, на 12000.

In [146]:
# напишите свой код тут
df['Salary'] = df['Salary'].where(df['Salary'] >= 60000, 12000)
df

,Unnamed: 0,Name,last_name,Age,City,is_closed,home_town,in_group,male_dummy,likes_memes,Salary,like_memes_scal
0,0,Alica,Larin,NaN,Moscow,False,Samara,True,0,5.0,400000,0.093023
1,1,Boris,Ivanov,27.0,Moscow,True,Saratov,True,1,8.0,190000,0.162791
2,2,Slava,Sidorov,64.0,Saint Peterburg,False,Saint Peterburg,False,1,44.0,130000,1.000000
3,3,Dmitriy,Alekseev,32.0,NaN,True,NaN,False,1,NaN,70000,NaN
4,4,Evgenia,Petrov,29.0,Moscow,False,Moscow,True,0,1.0,230000,0.000000
5,5,Boris,Lebedev,44.0,Saint Peterburg,True,Moscow,True,1,12.0,150000,0.255814
6,6,Dmitriy,Aksenov,NaN,Saint Peterburg,False,Kirov,False,1,11.0,70000,0.232558

34. Создайте многоуровневый индекс 'City' и 'Name'

In [149]:
# напишите свой код тут
df_multi=df.set_index(['City', 'Name'])
df_multi

                         Unnamed: 0 last_name   Age  is_closed  \
City            Name
Moscow          Alica             0     Larin   NaN      False
                Boris             1    Ivanov  27.0       True
Saint Peterburg Slava             2   Sidorov  64.0      False
NaN             Dmitriy           3  Alekseev  32.0       True
Moscow          Evgenia           4    Petrov  29.0      False
Saint Peterburg Boris             5   Lebedev  44.0       True
                Dmitriy           6   Aksenov   NaN      False

                               home_town  in_group  male_dummy  likes_memes  \
City            Name
Moscow          Alica             Samara      True           0          5.0
                Boris            Saratov      True           1          8.0
Saint Peterburg Slava    Saint Peterburg     False           1         44.0
NaN             Dmitriy              NaN     False           1          NaN
Moscow          Evgenia           Moscow      True           0          1.0
Saint Peterburg Boris             Moscow      True           1         12.0
                Dmitriy            Kirov     False           1         11.0

                         Salary  like_memes_scal
City            Name
Moscow          Alica    400000         0.093023
                Boris    190000         0.162791
Saint Peterburg Slava    130000         1.000000
NaN             Dmitriy   70000              NaN
Moscow          Evgenia  230000         0.000000
Saint Peterburg Boris    150000         0.255814
                Dmitriy   70000         0.232558

35. Используйте xs, чтобы выбрать данные для города "Moscow"

In [150]:
# напишите свой код тут
df_multi.xs('Moscow', level='City')

,Unnamed: 0,last_name,Age,is_closed,home_town,in_group,male_dummy,likes_memes,Salary,like_memes_scal
Name,,,,,,,,,,
Alica,0,Larin,NaN,False,Samara,True,0,5.0,400000,0.093023
Boris,1,Ivanov,27.0,True,Saratov,True,1,8.0,190000,0.162791
Evgenia,4,Petrov,29.0,False,Moscow,True,0,1.0,230000,0.000000

36. Используйте xs, чтобы выбрать данные для человека с именем "Boris"

In [151]:
# напишите свой код тут
df_multi.xs('Boris', level='Name')

,Unnamed: 0,last_name,Age,is_closed,home_town,in_group,male_dummy,likes_memes,Salary,like_memes_scal
City,,,,,,,,,,
Moscow,1,Ivanov,27.0,True,Saratov,True,1,8.0,190000,0.162791
Saint Peterburg,5,Lebedev,44.0,True,Moscow,True,1,12.0,150000,0.255814

37. Вычислите суммарную зарплату всех людей.

In [152]:
# напишите свой код тут
df['Salary'].sum()

np.int64(1240000)

38. Вычислите среднюю зарплату всех людей нашего Dataframe.

In [154]:
# напишите свой код тут
df['Salary'].mean()

np.float64(177142.85714285713)

39. Вычислите медиану возраста сотрудников.

In [155]:
# напишите свой код тут
df['Age'].median()

32.0

40. Вычислите стандартное отклонение зарплаты

In [156]:
# напишите свой код тут
df['Salary'].std()

114413.61890297933

41. Вычислите минимальную и максимальную зарплату

In [163]:
# напишите свой код тут
min_sal = df['Salary'].min()
max_sal = df['Salary'].max()

42. Вычислите минимальный и максимальный возраст сотрудников.

In [162]:
# напишите свой код тут
min_age = df['Age'].min()
max_age = df['Age'].max()